name: BestProxy

on:
  schedule:
      - cron: '*/10 * * * *'
  #push:
  branches:
      - main
       paths:
         - bestproxy.txt
  

jobs:
  update_dns:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: BestProxy
      run: |
        python .github/workflows/bestproxy.py
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
